-- Migration: Add Newsletter and News Collection Features
-- Created: 2026-01-27

-- =====================================================
-- 1. NEWSLETTER SETTINGS TABLE
-- =====================================================
CREATE TABLE newsletter_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  subscription_id UUID UNIQUE NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,

  -- Email configuration
  recipient_email TEXT NOT NULL,
  sender_name TEXT DEFAULT 'RSS Aggregator',

  -- Schedule
  frequency TEXT NOT NULL DEFAULT 'daily', -- 'hourly', 'daily', 'weekly'
  send_time TIME DEFAULT '09:00:00',
  send_day_of_week INTEGER, -- 0-6 for weekly (0 = Sunday)
  is_active BOOLEAN DEFAULT TRUE,

  -- LLM prompts (user-configurable)
  filter_prompt TEXT NOT NULL,
  summary_prompt TEXT NOT NULL,

  -- LLM configuration
  llm_provider TEXT DEFAULT 'anthropic', -- 'anthropic', 'openai'
  llm_model TEXT DEFAULT 'claude-3-5-sonnet-20241022',

  -- Template
  subject_template TEXT DEFAULT 'Your Newsletter - {{date}}',

  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  -- Constraints
  CONSTRAINT valid_frequency CHECK (frequency IN ('hourly', 'daily', 'weekly')),
  CONSTRAINT valid_day_of_week CHECK (send_day_of_week IS NULL OR (send_day_of_week >= 0 AND send_day_of_week <= 6)),
  CONSTRAINT valid_llm_provider CHECK (llm_provider IN ('anthropic', 'openai'))
);

CREATE INDEX idx_newsletter_settings_subscription ON newsletter_settings(subscription_id);
CREATE INDEX idx_newsletter_settings_active ON newsletter_settings(is_active) WHERE is_active = TRUE;

-- =====================================================
-- 2. NEWSLETTER SENDS TABLE
-- =====================================================
CREATE TABLE newsletter_sends (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  subscription_id UUID NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
  newsletter_settings_id BIGINT NOT NULL REFERENCES newsletter_settings(id) ON DELETE CASCADE,

  sent_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  recipient_email TEXT NOT NULL,
  subject TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'sent', 'failed', 'viewed'

  html_content TEXT NOT NULL,
  summary_content TEXT,

  email_provider_id TEXT, -- Resend message ID
  error_message TEXT,

  news_ids BIGINT[] NOT NULL DEFAULT '{}',
  news_count INTEGER NOT NULL DEFAULT 0,

  viewed_at TIMESTAMPTZ,
  view_count INTEGER DEFAULT 0,

  llm_tokens_used INTEGER,
  processing_duration_ms INTEGER,

  -- Constraints
  CONSTRAINT valid_status CHECK (status IN ('pending', 'sent', 'failed', 'viewed'))
);

CREATE INDEX idx_newsletter_sends_subscription ON newsletter_sends(subscription_id);
CREATE INDEX idx_newsletter_sends_sent_at ON newsletter_sends(sent_at DESC);
CREATE INDEX idx_newsletter_sends_status ON newsletter_sends(status);
CREATE INDEX idx_newsletter_sends_settings ON newsletter_sends(newsletter_settings_id);

-- =====================================================
-- 3. NEWS COLLECTION SOURCES TABLE
-- =====================================================
CREATE TABLE news_collection_sources (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'rss', 'tavily_search'
  is_active BOOLEAN DEFAULT TRUE,

  -- RSS-specific
  rss_url TEXT,

  -- Tavily-specific
  tavily_query TEXT,
  tavily_search_depth TEXT DEFAULT 'basic', -- 'basic', 'advanced'
  tavily_days INTEGER DEFAULT 1,

  -- Schedule
  collection_frequency TEXT DEFAULT 'hourly', -- 'hourly', 'daily', 'weekly'
  last_collected_at TIMESTAMPTZ,
  next_collection_at TIMESTAMPTZ,

  -- Auto-tagging
  auto_tag_enabled BOOLEAN DEFAULT TRUE,
  llm_provider TEXT DEFAULT 'anthropic',
  llm_model TEXT DEFAULT 'claude-3-5-haiku-20241022', -- Cheaper for tagging

  total_items_collected INTEGER DEFAULT 0,
  last_error TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

  -- Constraints
  CONSTRAINT valid_type CHECK (type IN ('rss', 'tavily_search')),
  CONSTRAINT valid_rss_source CHECK (type != 'rss' OR rss_url IS NOT NULL),
  CONSTRAINT valid_tavily_source CHECK (type != 'tavily_search' OR tavily_query IS NOT NULL),
  CONSTRAINT valid_collection_frequency CHECK (collection_frequency IN ('hourly', 'daily', 'weekly')),
  CONSTRAINT valid_search_depth CHECK (tavily_search_depth IN ('basic', 'advanced')),
  CONSTRAINT valid_llm_provider_collection CHECK (llm_provider IN ('anthropic', 'openai'))
);

CREATE INDEX idx_news_sources_active ON news_collection_sources(is_active) WHERE is_active = TRUE;
CREATE INDEX idx_news_sources_next_collection ON news_collection_sources(next_collection_at) WHERE is_active = TRUE;
CREATE INDEX idx_news_sources_type ON news_collection_sources(type);

-- =====================================================
-- 4. NEWS COLLECTION RUNS TABLE
-- =====================================================
CREATE TABLE news_collection_runs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  source_id BIGINT NOT NULL REFERENCES news_collection_sources(id) ON DELETE CASCADE,

  started_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  completed_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'running', -- 'running', 'completed', 'failed'

  items_fetched INTEGER DEFAULT 0,
  items_new INTEGER DEFAULT 0,
  items_skipped INTEGER DEFAULT 0,

  duration_ms INTEGER,
  llm_tokens_used INTEGER,

  error_message TEXT,
  error_stack TEXT,

  -- Constraints
  CONSTRAINT valid_run_status CHECK (status IN ('running', 'completed', 'failed'))
);

CREATE INDEX idx_news_runs_source ON news_collection_runs(source_id);
CREATE INDEX idx_news_runs_created ON news_collection_runs(created_at DESC);
CREATE INDEX idx_news_runs_status ON news_collection_runs(status);

-- =====================================================
-- 5. ALTER EXISTING TABLES
-- =====================================================

-- Update news table - Add source tracking
ALTER TABLE news
  ADD COLUMN source_id BIGINT REFERENCES news_collection_sources(id) ON DELETE SET NULL,
  ADD COLUMN collected_at TIMESTAMPTZ,
  ADD COLUMN auto_tagged BOOLEAN DEFAULT FALSE;

CREATE INDEX idx_news_source ON news(source_id);
CREATE INDEX idx_news_collected_at ON news(collected_at DESC);

-- Update subscriptions table - Add metadata
ALTER TABLE subscriptions
  ADD COLUMN name TEXT,
  ADD COLUMN description TEXT,
  ADD COLUMN has_newsletter BOOLEAN DEFAULT FALSE;

CREATE INDEX idx_subscriptions_has_newsletter ON subscriptions(has_newsletter) WHERE has_newsletter = TRUE;

-- =====================================================
-- 6. HELPER FUNCTIONS
-- =====================================================

-- Function to update next_collection_at based on frequency
CREATE OR REPLACE FUNCTION calculate_next_collection_time(
  frequency TEXT,
  from_time TIMESTAMPTZ DEFAULT NOW()
)
RETURNS TIMESTAMPTZ
LANGUAGE plpgsql
AS $$
BEGIN
  CASE frequency
    WHEN 'hourly' THEN
      RETURN from_time + INTERVAL '1 hour';
    WHEN 'daily' THEN
      RETURN from_time + INTERVAL '1 day';
    WHEN 'weekly' THEN
      RETURN from_time + INTERVAL '1 week';
    ELSE
      RETURN from_time + INTERVAL '1 hour';
  END CASE;
END;
$$;

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_newsletter_settings_updated_at
  BEFORE UPDATE ON newsletter_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_news_collection_sources_updated_at
  BEFORE UPDATE ON news_collection_sources
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 7. COMMENTS FOR DOCUMENTATION
-- =====================================================

COMMENT ON TABLE newsletter_settings IS 'Configuration for LLM-powered email newsletters per subscription';
COMMENT ON TABLE newsletter_sends IS 'Audit log of sent newsletters with delivery tracking';
COMMENT ON TABLE news_collection_sources IS 'Configuration for automated news collection from RSS feeds and Tavily search';
COMMENT ON TABLE news_collection_runs IS 'Audit log for news collection runs with statistics';

COMMENT ON COLUMN newsletter_settings.filter_prompt IS 'User-defined LLM prompt for filtering relevant news';
COMMENT ON COLUMN newsletter_settings.summary_prompt IS 'User-defined LLM prompt for generating newsletter summary';
COMMENT ON COLUMN newsletter_sends.news_ids IS 'Array of news item IDs included in this newsletter';
COMMENT ON COLUMN news.source_id IS 'Reference to the collection source that fetched this news item';
COMMENT ON COLUMN news.auto_tagged IS 'Whether tags were assigned by LLM auto-tagger';
