import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Link,
  Hr,
  Img,
} from '@react-email/components'
import * as React from 'react'

interface NewsletterEmailProps {
  summary: string
  newsItems: Array<{
    title: string
    url: string
    content: string
  }>
  trackingPixelUrl: string
}

export default function NewsletterEmail({
  summary,
  newsItems,
  trackingPixelUrl,
}: NewsletterEmailProps) {
  return (
    <Html>
      <Head />
      <Body style={main}>
        <Container style={container}>
          {/* Header */}
          <Section style={header}>
            <Text style={headerText}>📰 Your RSS Newsletter</Text>
          </Section>

          {/* Summary Section */}
          <Section style={summarySection}>
            <Text style={summaryTitle}>Summary</Text>
            <div dangerouslySetInnerHTML={{ __html: summary }} style={summaryContent} />
          </Section>

          <Hr style={hr} />

          {/* News Items */}
          <Section style={newsSection}>
            <Text style={newsSectionTitle}>Featured Articles ({newsItems.length})</Text>

            {newsItems.map((item, index) => (
              <div key={index} style={newsItem}>
                <Text style={newsItemTitle}>
                  <Link href={item.url} style={newsItemLink}>
                    {item.title}
                  </Link>
                </Text>
                <Text style={newsItemContent}>
                  {item.content.substring(0, 300)}
                  {item.content.length > 300 ? '...' : ''}
                </Text>
                <Text style={newsItemReadMore}>
                  <Link href={item.url} style={readMoreLink}>
                    Read more →
                  </Link>
                </Text>
                {index < newsItems.length - 1 && <Hr style={newsItemDivider} />}
              </div>
            ))}
          </Section>

          {/* Footer */}
          <Hr style={hr} />
          <Section style={footer}>
            <Text style={footerText}>
              This newsletter was generated by your RSS Aggregator with AI assistance.
            </Text>
            <Text style={footerText}>
              Powered by{' '}
              <Link href="https://www.anthropic.com" style={footerLink}>
                Claude AI
              </Link>
            </Text>
          </Section>

          {/* Tracking Pixel */}
          <Img src={trackingPixelUrl} width="1" height="1" alt="" style={trackingPixel} />
        </Container>
      </Body>
    </Html>
  )
}

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Ubuntu, sans-serif',
}

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
  maxWidth: '600px',
}

const header = {
  padding: '32px 20px',
  backgroundColor: '#4F46E5',
  borderRadius: '8px 8px 0 0',
}

const headerText = {
  color: '#ffffff',
  fontSize: '28px',
  fontWeight: 'bold',
  textAlign: 'center' as const,
  margin: '0',
}

const summarySection = {
  padding: '32px 20px',
}

const summaryTitle = {
  fontSize: '20px',
  fontWeight: 'bold',
  color: '#1f2937',
  margin: '0 0 16px 0',
}

const summaryContent = {
  fontSize: '16px',
  lineHeight: '24px',
  color: '#374151',
}

const hr = {
  borderColor: '#e5e7eb',
  margin: '20px 0',
}

const newsSection = {
  padding: '0 20px',
}

const newsSectionTitle = {
  fontSize: '20px',
  fontWeight: 'bold',
  color: '#1f2937',
  margin: '0 0 24px 0',
}

const newsItem = {
  marginBottom: '24px',
}

const newsItemTitle = {
  fontSize: '18px',
  fontWeight: '600',
  color: '#1f2937',
  margin: '0 0 12px 0',
}

const newsItemLink = {
  color: '#4F46E5',
  textDecoration: 'none',
}

const newsItemContent = {
  fontSize: '14px',
  lineHeight: '20px',
  color: '#6b7280',
  margin: '0 0 8px 0',
}

const newsItemReadMore = {
  margin: '0',
}

const readMoreLink = {
  color: '#4F46E5',
  textDecoration: 'none',
  fontSize: '14px',
  fontWeight: '500',
}

const newsItemDivider = {
  borderColor: '#f3f4f6',
  margin: '24px 0',
}

const footer = {
  padding: '20px 20px',
}

const footerText = {
  color: '#9ca3af',
  fontSize: '12px',
  textAlign: 'center' as const,
  margin: '4px 0',
}

const footerLink = {
  color: '#9ca3af',
  textDecoration: 'underline',
}

const trackingPixel = {
  display: 'none',
}
